---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
  namespace: default
spec:
  storageClassName: nfs-kube
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
