---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: authelia-tunnel
  namespace: default
subjects:
  - name: authelia
    spec:
      fqdn: auth.zweifel.cloud
tunnelRef:
  kind: ClusterTunnel
  name: cluster-tunnel
