---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.9@sha256:e10ff50f840eb2cb30d8eb676cad09eb7feee49e7463bd10bf91cb174879de4f

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 65539

    env:
      DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "10.0.0.235"
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host jellyfin.zweifel.cloud
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: jellyfin-tls

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      nfs-nas-media:
        enabled: true
        mountPath: /data/nas-media
        path: /srv/nfs4/media
        server: 10.0.0.119
        type: nfs
      transcode:
        enabled: true
        type: emptyDir

    resources:
      requests:
        cpu: 100m
        memory: 1000M
      limits:
        memory: 3G
