---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: echo-server-tunnel
  namespace: default
subjects:
  - name: echo-server
    spec:
      fqdn: echo-server.zweifel.cloud
tunnelRef:
  kind: ClusterTunnel
  name: cluster-tunnel
