---
access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain: ["pihole.zweifel.cloud"]
      policy: bypass
    - domain: ["wizarr.zweifel.cloud"]
      resources: ["^/join.*$", "^/j/.*$", "^/setup.*$", "^/static/.*$"]
      policy: bypass

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: weave-gitops
        description: Weave GitOps
        secret: "{{ .WEAVEGITOPS_OAUTH_CLIENT_SECRET }}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email", "offline_access"]
        redirect_uris: ["https://gitops.zweifel.cloud/oauth2/callback"]
        userinfo_signing_algorithm: none
log:
  level: debug
  format: text
  keep_stdout: true
