---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metallb-git
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/metallb/metallb
  ref:
    commit: 6a5ad674b791ca00ab6f797023a2a04d5b7903aa
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/charts/metallb
