---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metallb-git
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/metallb/metallb
  ref:
    commit: ca4eed32d1f60b2ffc29c3afd85e2a9be2821d16
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/charts/metallb
