---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
commonLabels:
  app.kubernetes.io/name: jellyfin
  app.kubernetes.io/instance: jellyfin
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
