kind: ENC[AES256_GCM,data:KqChUIDu,iv:9PqSP3nrZlxZD8PuweraFItAyFdrjqApQgFAD7b++Oo=,tag:0H/sQkm+tLKTAuMa2kjZXw==,type:str]
ansible_user: ENC[AES256_GCM,data:CghF00o=,iv:RKZUIsLOdj8hBwF3dz+nJiuCQqzLYwJmjc8KhEkhOQY=,tag:zOIL/s3NwbyNS/2OgU4lYQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:rn124x8mnOk5sDgDKX0HNwsqiKiK,iv:vLhpH7du+7Aq382RJ85NwYZcZ8JaaiSPb2d3avH21/A=,tag:GnAc2s0421ZN4b8guO+ejA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ruc6fxxhu0swq2qmdpkveyhgjlu9d5rg6p59xv9npn20e7ay09fqrcpgm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdVdhaCtPOHlWK0V5M2ky
            ZW5SU2pDSnJJb2hKbTd6L2dhMHpYdmMzNXk4Cm1Pd2NWTUR2TnFLU052SGdRMXVs
            YzRPZndzYkxYZ0N6S2RhdlgrSjBJRjAKLS0tIGVKaE0zbnYxNkEvQXBkUGFMWDNm
            eXMzWFd0czBDQUtpdlVJVkYyOWlTVm8KztBdRBHMo0/Wkc/bORt6egP3hzyqvjtX
            ZX0KKhG9NXvpqYylggahM5hlT4Dx8UCzfLYc+QAe0eFI48GP6zWMjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T00:57:24Z"
    mac: ENC[AES256_GCM,data:xFqLxGJXnZqmKQy0buJcKI/w0kex7p8Xeayoq5vm1TicwtavTjSKKC6Teg/9phzSmSIAh4P437Q4DIn8PGjvlmKYhHEWt1BuwBv2urmeiahvLgcQtarAAmJEbrIYf+4/ug6wnyBDNj7AmNjkM6qLe1OsVj9oszktvXKSRL62ccw=,iv:Vl527v2/k/abiAfXtKrRCbDAEuDVKFai5vYm+I/NFgQ=,tag:L4OlIpHbuXVGWyJWIsczwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
