---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./external-secrets.yaml
  - ./mojo2600.yaml
  - ./k8s-at-home-charts.yaml
  - ./angelnu.yaml
  - ./beezlabs.yaml
  - ./longhorn.yaml
