---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: cronjob
      cronjob:
        schedule: "@daily"
        ttlSecondsAfterFinished: 86400
    restartPolicy: OnFailure
    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: edge@sha256:ba2249469aa08689da02695e9822c69877ca675daf8c38d6debe913fe16d2596
    command: ["/app/recyclarr/recyclarr"]
    args: ["sync"]
    envFrom:
      - secretRef:
          name: radarr-secret
      - secretRef:
          name: sonarr-secrets
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        subPath: recyclarr.yml
        mountPath: /config/recyclarr.yml
        defaultMode: 0775
        readOnly: true
