apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:6igMjgIra9U3ATT3rakOkodbwNJdVb1ECfBujY4laFwqpX2iHQ==,iv:P/lraGVcU/2lsnfg3RoJem6uXM9CpjjMsTomDps5zVA=,tag:T04dSL1J3Pd8ialHD1Z1wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ruc6fxxhu0swq2qmdpkveyhgjlu9d5rg6p59xv9npn20e7ay09fqrcpgm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V0Q5Q29adC9senJiWWIz
            U3kwR0RkWlk2UVJHY1I0eHdFZkJrYzg5QnkwCnBsVU4rWDR5YjZpc1JSUnlOdzBy
            V0xhWCtCcjVwdldKQTFyWWFLdkNHSk0KLS0tIEV6RjdEamJCRGlFeTJJWTJjZDJx
            SXdmeldVTHd0S2I0dGR2TWtZRjNxRlUKxx6zT7Gvw3Z+whGKXY8DntkCOmaBcgs4
            gjecFrH1ijni9rB9CrKkLyxqFCj3IKVDZ3MkikwjUdBlP25ichOFiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T00:57:24Z"
    mac: ENC[AES256_GCM,data:TP3cb4lQKL7iOdQmvA60R7FX0542BljWlbWA+Qz1yMtpfNwFihVYND6GfMMeehHAImv6YukxdTnUofqOeecdLhF8XI2fa0ziGlJpddDwRoKPQdDKsuyVtSPZE0Z71e13t2Xu1wDutd0HL+EDy6KaJacbHnw/hUHvc4iibPO85bY=,iv:Bk5NVjJSaxfSHB4PSD3/8FqlfswsO9qkE8PjN/f+eak=,tag:VJ3OfmeYekBUS73WXrmJSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
