apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:+ekLjWnFyD7DwsjSlnRQBpJo,iv:/lJPb+eIhH5MfX+TCjR7pKLz34lf8i+hFYl44rZbyR4=,tag:xGrZ4ZRd4QWqw7cTSef/5Q==,type:str]
    api-key: ENC[AES256_GCM,data:G2+NIEpw5j71+qgAr6G1LlLketq8FlL0tJnP+R1l0UvoaoR6SQ==,iv:r4X/5uVrrc3nz49gn1lzGOMeS6j78Xy1u6b/CRPJKkE=,tag:/4B/Xj+LLn8EeLaA4U7zSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ruc6fxxhu0swq2qmdpkveyhgjlu9d5rg6p59xv9npn20e7ay09fqrcpgm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSm5mUzhPckhncEIrSng0
            ZUN5L3BzSzIybCt0dVg1QjV0MDJzZm1UYVE4CkhYUjU3TytuVXV3U29jV29MU2NW
            S3RDdlZVVkRNRmtQemJmY2xrdi9hVHMKLS0tIEI2a0U5c0JMeTNTOGE2dmpxdTRR
            M0dVM2tSSFBWd1VzN29wNlk3Uk4rUFUKtBfq0wfqOjmQAgUuUJH5Vh91ivhmY2Sx
            Cbw51mo/Q+77oLetlqCAwZs1cg0AWVVVA7qzJxvLTkcT7LKtCOU4Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-07T21:28:21Z"
    mac: ENC[AES256_GCM,data:eZrBd3k54gmmJTDwxKvB1tOBHmCFKBfRvYz0ko1V4DID6r6V/LbcyW+roG2+jiBO/i4jdF/B+a45HRnndR5leo81C9v6cWPtbaPEa7/nNXcZbeQAFsSem9E/LEZ7VHn6iDv96JVvVL3UBUdTGXQOU74OYpOjtZq0CrB4q9rzFX4=,iv:Wyc1rqFuL8roHTwkKtXtQPqpgeMvT4YlkKGN61K5J5w=,tag:5SdPJlbHFAuXUea2hcJXiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
