---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel-operator
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflare-tunnel-operator
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: beezlabs
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/beezlabs-org/cloudflare-tunnel-operator
      pullPolicy: IfNotPresent
      tag: v0.2.0
    namespace:
      create: false
