---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prowlarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # PROWLARR__API_KEY
        key: prowlarr
