---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-operator
  namespace: cloudflare-operator-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-operator-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_TOKEN }}"
        CLOUDFLARE_API_KEY: "{{ .CLOUDFLARE_APIKEY }}"
  dataFrom:
    - extract:
        key: cloudflare
