---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-operator-system
resources:
  - ./externalsecret.yaml
  - ./cluster-tunnel.yaml
generatorOptions:
  disableNameSuffixHash: true
