---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd-secrets
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-secrets
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: sabnzbd
        property: api_key
    - secretKey: nzb_key
      remoteRef:
        key: sabnzbd
        property: nzb_key
