---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./pvc-longhorn.yaml
  - ./externalsecret.yaml
commonLabels:
  app.kubernetes.io/name: sabnzbd
  app.kubernetes.io/instance: sabnzbd
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
