---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-longhorn
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: longhorn
