---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudflare-tunnel-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets
    - name: cluster-apps-metallb-config
  path: ./kubernetes/apps/networking/cloudflare-tunnel-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cloudflare-tunnel-operator
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudflare-tunnel-operator-tunnels
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudflare-tunnel-operator
  path: ./kubernetes/apps/networking/cloudflare-tunnel-operator/tunnels
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
