---
# (string) Timezone for the servers
timezone: "America/Chicago"

# (list) Additional ssh public keys to add to the nodes
# ssh_authorized_keys:

ubuntu:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - nano
    - nfs-common
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-yaml
    - python3-pip
