---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-secrets
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        # PUSHOVER_TOKEN, SONARR__API_KEY
        key: sonarr
    - extract:
        # PUSHOVER_USER_KEY
        key: pushover
