---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.14
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      username: admin
    oidcSecret:
      create: true
      clientID: weave-gitops
      issuerURL: https://auth.zweifel.cloud
      redirectURL: https://gitops.zweifel.cloud/oauth2/callback
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: |
          10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hajimari.io/icon: sawtooth-wave
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/enable-cors: "true"
      hosts:
        - host: &host "gitops.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: weave-gitops-tls
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
    podAnnotations:
      secret.reloader.stakater.com/reload: weave-gitops-secret
  valuesFrom:
    - kind: Secret
      name: weave-gitops-secret
      valuesKey: adminPassword
      targetPath: adminUser.passwordHash
    - kind: Secret
      name: weave-gitops-secret
      valuesKey: WEAVEGITOPS_OAUTH_CLIENT_SECRET
      targetPath: oidcSecret.clientSecret
