apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:+8pPl+Y/JimO9Teas5CeTX7Ofu/0SCdho2v83nfXVS0V4zQVJXnK5jbhkCf4aSBImD9VBN6fh+OptIaq,iv:NoEqvbETngMSm/LhQrIP1ey3uYEiLHVWT6g/JecNstE=,tag:J5dOST/e092EUfIFXX5cnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ruc6fxxhu0swq2qmdpkveyhgjlu9d5rg6p59xv9npn20e7ay09fqrcpgm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUzA2eHVqUTNhUlp5VUxF
            MDdYWFc4bXRzRDBzOG5lRXE5bm9DS2k5N0VjCmQxVkZycDkrOUJrQ1VqZ21VY0sw
            Ym1salVrNlFHeHdJbitKMnJqOThKb28KLS0tIDdtT0kzR3BWdEt0WmJ1dzBPck9y
            NUFRdDUvSjJFd1BDNmJLd29pWnVHa3cKMpDefVkccxlZHUoosuk2TtcUbrjUc9Ma
            BM90d2apcNXpF5sPVJ1Au3UO4eupCG+lhPXn9V+0jphB8B0/af48PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T13:42:17Z"
    mac: ENC[AES256_GCM,data:GbsQgh9GKK1jriYTGwbxeYGXUfyJinMvvAeAfmywAmtyyLZ6Ws7L7Z2T1jS49VPZ53d9DgcC9lsEQqtIx410j9oqFp5dW/vDnj0te43ttRC+fznaljnIAMmL7PkO9tfts8yUwJewMyyFX5UxGQ46ugBmPe6QSKSba9wWWyz8l/I=,iv:5T/F199GPrixXBQfXS4tRsD2RbUcginewjvzRHfQnWg=,tag:NolCybUEkEPhi510wuE69A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
