apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:24sv3SyucjiEADYGl9ydN4xajnOtfxY99xtay8reUeASRBIqJrCYLqbwGmWtN29y/Hpx8+IqWRkHgfJo,iv:daj1YtCe52EtyFoJJ80XGBfBO/huia6blovcp1RWqUo=,tag:rfQpEfcxcr02W5IYC+EnWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ruc6fxxhu0swq2qmdpkveyhgjlu9d5rg6p59xv9npn20e7ay09fqrcpgm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVHpkYjV2QVRkU2RpeG8y
            MEdJaGg3MjUrWnc5VlIzc1diRVRaUjcrdlNnClRWd296bHB0SmdpMUs3eXFuOWhZ
            OGFTRU14Ymk5NmlOSWp0cTZLRGRqQ1EKLS0tIHFPRmthTVpYemthRUVRLzNDWGx2
            a282TjRJOHFRazhaemZ4VGtmS0Exb2MKvQ/K6XB/umUCiqmSjBjSSnV3LsPcSi+M
            Wed2Sdh84b/rU9E40jPO5DesAMt6SblFguWq98VKvzgX3onZNax4MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T00:57:24Z"
    mac: ENC[AES256_GCM,data:3MOWEOljvpoNNtAePJTSQRyPTQVTP3QZbh2X2qAXVEEZopjNkcg8Az9utJkjmpkkXJ/1YVbkZDnxw+F0oD/1ELnAT3i4yQbVTCEBqu3NjSHOUFuFrPkZiSLvOTObuaCseG43AFzmfThFjmWMYOxRSs4qPqRjokZQNOoUL45QbUw=,iv:jSJiRybB7dNX7lNDYyCEFfgw71K4v7wZZN8ZZIpNIp0=,tag:MZmLV8HnyB+lTAR/CzlHUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
