---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-recyclarr
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-radarr
    - name: cluster-apps-sonarr
  path: ./kubernetes/apps/downloads/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
