apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DJe47IZYaj3UcJWZ/Q==,iv:zK6TiL6zvuYveQrBqi0mMjhtmb3s2lPivK2MbLr9u1o=,tag:BUnd8WdcYKLkelxTT0/YtQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:q4XaG+RWF516KC2zKIhbU25X,iv:CnMi7uRo73m9zIWF6wl0l0n+CP5nrfRj9s5VFdB6lSc=,tag:8xeWPfjCUF+YjMFByflHOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ruc6fxxhu0swq2qmdpkveyhgjlu9d5rg6p59xv9npn20e7ay09fqrcpgm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VzA1bWFSZ2RHL2kyNUYr
            eHp1V2wvNWFaYWViUmdlTnFZaE1EK0gwdkI0CmlnZWJBUlQ3NnUrNkNRcE8vdUYv
            VmlDaG5yclBNbTJSWTd3RGpVZlVYK2cKLS0tIG9CeHVMdExxdXpibDlkc3BhVG9Z
            K3ZWMm5Hamh6R3k0QUVzY2lrQXZwRUUKjx8ikJ5SVMDWLwS6tOkzILhZaNSi/4NM
            9BRCyEYZIXCgFwQpqMnlQmVvikNyTnQ3yWCqOhHNGXGu911PHBWIjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T18:54:25Z"
    mac: ENC[AES256_GCM,data:cmHGRJith/pcMAO2CUYcMjuVakL9JHoXiB9LtiYMON8N745za1gW8iPZPqwYoUIlFlCJoTy4nQlVhc/ljHfY1H2GZ9OCp9z87S4alHzZiWTayeDzcr+B9GFGBhMq/rLqY9p+8jH3Hc4sfbqtcp/U3Uc35XJ/o/P+b/mPbCWS4Uk=,iv:oT/wsa7ZwjwRdR9tW4MDs6baNHDa5zyyAxLMJ8TNMHo=,tag:tjmOV8cUuAlDsDnnWMkQKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
