apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1E20v4Pel4bBonO3qQ==,iv:h9OUaktXAe7580RAZih3hYXUeJf3lppwCit+vcic+WU=,tag:8r1TCq/0+yG51IVtYdcsdQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:T9fFG3rjazn1uYcW8vHW9q+y,iv:etkElPSIS+vTvwo1bbz9e8dwsiw8GQMnXES9/w8RAis=,tag:KFT1VhwWmezk8+tCT/OO8w==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:3rCxZm+STpI2MjnpdK6ix9c2iOwskTlqh/Mdd8Jp,iv:DlNymWWnQz8SUeEbCCfNYUHQzdwuGZDxACNBLPKKbMM=,tag:yoxQrtNySTccd4IQOywQlw==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:XWGNJ8OGgMCznv0Qwe4VS8SNRDAiTe9F2Wl2rcLE,iv:6rB2VKW3gFZeSccHaiIOUgG4IxAEc1wPRSO/yxDQGwI=,tag:y2hEgXhN8Kn7Wiu17cgDxg==,type:str]
    SECRET_ALERTMANAGER_UPTIMEROBOT_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:MiFfeg==,iv:UFvoslIHQN7So4lfkrqxYHM2eRZip6YSRS0Q4ohLZ/k=,tag:d8pzddjMxecK3HKGMpk6pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ruc6fxxhu0swq2qmdpkveyhgjlu9d5rg6p59xv9npn20e7ay09fqrcpgm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISnZwbC9hdk9QL3UyanJj
            UVlqZHpzQUVUWEpjV3dYc0s4ZllsTU1ScWlnCk56cGtuc0k3ejNEMjhXVG1yaU1r
            dkhzQi9CYzNBT25YMnd0azdCdmt0QkUKLS0tIHpYLzdWRzFXVUNWdmVKQXl5T3RQ
            dGo2eHd3WU9KQ2xRd2tvYUFWU0ZieU0KrX+r5GXS6flmK1JBQrWaggkHUPHen6YX
            lG3fLVdk6XjLmk+pNAYb5SlMa9asmAqYofMRWXCAYhXgpYL9r9UJhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T19:12:38Z"
    mac: ENC[AES256_GCM,data:F39wTt2p0kWTy4plxkC8PwuoEO0cdTuuYm/qqOnzCiDAF5GDzG+fzaLyeJu10U6t9nf65VFbL7Net2SfZGvZ6lWlnfFcJYVZEoQICF+qBfBu+xw3iAjGqrDZIqby2OB04daMBXL8Mn/yOHVWF5xlevPD3aHV/56+R3BV9t0+T6k=,iv:LLtijG5LArqa1CxoiVK8Wouft1fuvCdmH5CHH1rpe3s=,tag:cxvnVvfAGTc3bhSP0NGaYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
