---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "10.0.0.199"
  METALLB_LB_RANGE: "10.0.0.230-10.0.0.250"
  METALLB_K8S_GATEWAY_ADDR: "10.0.0.230"
  METALLB_INGRESS_ADDR: "10.0.0.231"
