---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: downloads-gateway-vpnconfig
  namespace: vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: downloads-gateway-vpnconfig
    creationPolicy: Owner
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: prowlarr
        property: OPENVPN_USER
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: prowlarr
        property: OPENVPN_PASSWORD
