---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./tunnelbinding.yaml
labels:
  - pairs:
      app.kubernetes.io/name: overseerr
      app.kubernetes.io/instance: overseerr
