---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # https://github.com/metallb/metallb/commit/ef822134600bf9ce2a0365cc9a0e7cc5752c8269
      # https://github.com/MoJo2600/pihole-kubernetes/issues/248
      chart: charts/metallb
      sourceRef:
        kind: GitRepository
        name: metallb-git
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      enabled: true
    psp:
      create: false
    controller:
      image:
        tag: main
    speaker:
      image:
        tag: main
