---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pihole-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PIHOLE_ADMIN_PASS: "{{ .PIHOLE_ADMIN_PASS }}"
  dataFrom:
    - extract:
        key: pihole
