---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 2.11.1
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    strategyType: RollingUpdate
    maxSurge: 1
    maxUnavailable: 1
    dnsHostPort:
      enabled: true
      port: 53
    serviceDns:
      mixedService: true
      type: LoadBalancer
      port: 53
      loadBalancerIP: "10.0.0.232"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        externalTrafficPolicy: Local
    serviceDhcp:
      enabled: false
    serviceWeb:
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443
      type: LoadBalancer
      loadBalancerIP: "10.0.0.232"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    virtualHost: pihole
    ingress:
      enabled: true
      ingressClassName: nginx
      path: /
      hosts:
        - &host "pihole.zweifel.cloud"
      tls:
        - hosts:
            - *host
          secretName: pihole-tls
      annotations:
        hajimari.io/icon: mdi:raspberry-pi
        hajimari.io/url: "https://pihole.zweifel.cloud/admin"
        hajimari.io/group: "networking"
        hajimari.io/targetBlank: "true"
        hajimari.io/info: "DNS Server and Ad Blocker"
        cert-manager.io/cluster-issuer: letsencrypt-production
    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 60
        failureThreshold: 10
        timeoutSeconds: 5
        port: http
        scheme: HTTP
      readiness:
        enabled: true
        initialDelaySeconds: 60
        failureThreshold: 3
        timeoutSeconds: 5
        port: http
        scheme: HTTP
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-pvc-longhorn
    admin:
      existingSecret: "pihole-secret"
      passwordKey: "PIHOLE_ADMIN_PASS"
    extraEnvVars:
      TZ: "America/Chicago"
    DNS1: "${METALLB_K8S_GATEWAY_ADDR}"
    DNS2: "1.1.1.1"
