---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-longhorn
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
