---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HASS_DB_ADMIN_PASSWORD: "{{ .HASS_DB_ADMIN_PASSWORD }}"
        HASS_DB_PASSWORD: "{{ .HASS_DB_PASSWORD }}"
        HASS_TOKEN: "{{ .HASS_TOKEN }}"
  dataFrom:
    - extract:
        key: home-assistant
