---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  values:
    image:
      # https://hub.docker.com/r/haveagitgat/tdarr_node
      repository: docker.io/haveagitgat/tdarr
      tag: latest
    env:
      TZ: "America/Chicago"
      webUIPort: 8265
      serverIP: 0.0.0.0
      serverPort: 8266
      ffmpegPath: ""
      PUID: 568
      PGID: 568
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
    service:
      main:
        ports:
          http:
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266
    persistence:
      config:
        enabled: true
        existingClaim: tdarr-config
        subPath:
          - path: tdarr/config
            mountPath: /app/configs
          - path: tdarr/data
            mountPath: /app/server
      media:
        enabled: true
        type: nfs
        server: 10.0.0.119
        path: /srv/nfs4/media
        mountPath: /data/nas-media
      # Transcode dir
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: material-symbols:switch-video-outline
        hosts:
          - host: &host "tdarr.zweifel.cloud"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: tdarr-tls
    sidecars:
      node:
        name: node
        image: docker.io/haveagitgat/tdarr_node:latest
        env:
          - name: TZ
            value: "America/Chicago"
          - name: nodeID
            value: node01
          - name: serverIP
            value: localhost
          - name: serverPort
            value: 8266
          - name: ffmpegPath
            value: ""
          - name: PUID
            value: 568
          - name: PGID
            value: 568
        volumeMounts:
          - name: config
            mountPath: /app/configs
          - name: media
            mountPath: /data/nas-media
          - name: shared
            mountPath: /shared
        # resources: {}
        affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
