---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: lidarr
      app.kubernetes.io/instance: lidarr
