---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.30.2.6563-3d4dc0cce@sha256:d0d3e5e75f5ed86843d123cd84bb1f54a0593ec26c908410548862607af880bf

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "10.0.0.234"
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        ingressClassName: nginx
        hosts:
          - host: &host plex.zweifel.cloud
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: plex-tls

    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      nfs-nas-media:
        enabled: true
        mountPath: /data/nas-media
        path: /srv/nfs4/media
        server: 10.0.0.119
        type: nfs
      transcode:
        enabled: true
        type: emptyDir

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 65539
    resources:
      requests:
        cpu: 100m
        memory: 1000M
      limits:
        memory: 4G
